collections:
  authors:
    output: true

prose:
  media: assets/img/
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "multiselect"
          label: "Author"
          options:
            - name: "Jill Watson"
              value: "jill Watson"
      - name: "img"
        field:
          element: "text"
          label: "Cover image"
          help: "Upload the image and type in the file name of the image precisely"
